### ISSUE TITLE
Application crashes when attempt to run application.py

### ISSUE THREAD

**Issue by Yonodactyl** [rsteel1/text_editor#9]
**Describe the bug**
Installing this package went fine.
When running application file there was an error.

**To Reproduce**
1. Installed git clone into virtual environment.
2. Run `python application.py`
3. See error

**Expected behavior**
I expected the application to launch and run.

**Desktop (please complete the following information):**
 - OS: MacOS 10.14

**Additional context**
```
  File "application.py", line 19, in __init__
    self.style.theme_use('vista')
  File "/anaconda3/lib/python3.6/tkinter/ttk.py", line 529, in theme_use
    self.tk.call("ttk::setTheme", themename)
_tkinter.TclError: can't find package ttk::theme::vista
```

**Comment by rsteel1** [comment]
Is this because you're running it using an Anaconda distribution?

Could you try with the official distribution and let me know if the error
still occurs?

https://www.python.org/downloads/release/python-370/

**Comment by rsteel1** [comment]
Oh no, I think this might be because you're running on Mac and the theme I've used is native for Windows, I never thought about that - I'll add some platform handling in for it.

**Comment by rsteel1** [comment]
Added some simple platform handling to application.py, tested on macOS Sierra - seems to be working alright now. Closing.
